
col_date: "DATE"

data_map_dict:
    dff: 
        data_ref: "DFF"
        data_source: "FRED"

     
    frb_kc_lmci_monthly:
        data_ref: "FRBKCLMCILA"
        data_source: "FRED"
    
    michigan_csi_monthly:
        data_ref: "UMCSENT"
        data_source: "FRED"

        
    rate_aus_3m_bank:
        data_ref: "IR3TIB01AUM156N"
        data_source: "FRED"

        
    rate_cnd_3m_bank:
        data_ref: "IR3TIB01CAM156N"
        data_source: "FRED"
        

    rate_chf_3m_bank:
        data_ref: "IR3TIB01CHM156N"
        data_source: "FRED"
        
    rate_deu_3m_bank:
        data_ref: "IR3TIB01DEM156N"
        data_source: "FRED"
        
    rate_eur_3m_bank:
        data_ref: "IR3TIB01EZM156N"
        data_source: "FRED"
        
        
    rate_gbp_3m_bank:
        data_ref: "IR3TIB01GBM156N"
        data_source: "FRED"
        
    rate_jpn_3m_bank:
        data_ref: "IR3TIB01JPM156N"
        data_source: "FRED"
        
        
    rate_deu_lt_gov:
        data_ref: "IRLTLT01DEM156N"
        data_source: "FRED"
    
    rate_eur_lt_gov:
        data_ref: "IRLTLT01EZM156N"
        data_source: "FRED"
        

    cpi_usa:
        data_ref: "USACPALTT01CTGYM"
        data_source: "FRED"
        
    cpi_eur:
        data_ref: "EA19CPALTT01GYM"
        data_source: "FRED"

        
    cpi_deu:
        data_ref: "DEUCPALTT01CTGYM"
        data_source: "FRED"
        
    cpi_gbr:
        data_ref: "GBRCPALTT01CTGYM"
        data_source: "FRED"


    cpi_chf:
        data_ref: "CHECPALTT01CTGYM"
        data_source: "FRED"

    cpi_jpn:
        data_ref: "CPALTT01JPM659N"
        data_source: "FRED"

        
    cpi_can:
        data_ref: "CANCPALTT01CTGYM"
        data_source: "FRED"


    cpi_aus:
        data_ref: "CPALTT01AUQ659N"
        data_source: "FRED"

        


